### ISSUE TITLE
Events created every 30 seconds

### ISSUE THREAD

**Issue by ZTRossouw** [juliusloman/dynatrace-oneagent-plugin-sslcertcheck#4]
I had set the "Interval between checks (hours)" to 24 to check once a day, but it seems that the same Certificate is creating an event every 30 seconds. I am still looking at the python file to see if I can find why, but I was hoping you could give me some insight as to why this is happening?

![cert](https://user-images.githubusercontent.com/47577028/102633526-2cb3d100-4116-11eb-8fad-617001deea44.PNG)

Thank you

**Comment by juliusloman** [comment]
Hello,
please try to use latest release ( https://github.com/juliusloman/dynatrace-oneagent-plugin-sslcertcheck/releases/tag/1.02 ).
Also there is currently a bug in OneAgent extension engine, that will be resolved in OneAgent 1.207. Current latest GA version 1.205 has a event deduplication bug and events do not deduplicate. The extension should work fine in 1.203. Which OneAgent version are you using?

**Comment by ZTRossouw** [comment]
I am currently using OneAgent 1.205. The updated plugin no longer creates duplicate events. I a have also waited and after the 2 hour refresh, there is still no new event. 

Thank you for the updates!
