### ISSUE TITLE
Limit reached: There is more than 20 properties for entity EntityType.PROCESS_GROUP_INSTANCE

### ISSUE THREAD

**Issue by ZTRossouw** [juliusloman/dynatrace-oneagent-plugin-sslcertcheck#5]
I am not sure if this is an actual issue or would have any effect on the plugin that you have created. But I could not find anything the plugin that sets a max amount of properties for any entity. Was hoping for some insight as to if this is a plugin problem or a Dynatrace problem.

![hosts](https://user-images.githubusercontent.com/47577028/102634866-160e7980-4118-11eb-979e-2e34e8965298.PNG)

 I have also been chatting with Dynatrace help center to see if they have an answer and will update accordingly.

Thank you

**Comment by juliusloman** [comment]
Hello,
please try to use latest release ( https://github.com/juliusloman/dynatrace-oneagent-plugin-sslcertcheck/releases/tag/1.02 ).
There have been improvements targeting the extension limits.
Thanks

**Comment by ZTRossouw** [comment]
1.02 solved extension limits issue.

Thank you
